### ISSUE TITLE
exception logged when performing --create_dashboard

### ISSUE THREAD

**Issue by baslerj** [IBM/spectrum-protect-sppmon#11]
The following exceptions are generated when running the --create_dashboard operation.  It appears some steps within sppmon.py need to be bypassed when performing a --create_dashboard.

```
Exception in FILE: rest_client.py, Line: 86, Exception: <class 'ValueError'>
Exception Message: Status Code Error in REST-API post data response
Exception args: (401, <Response [401]>, '/api/endeavour/session', None)
Please make sure your Hostadress, port, username and password for REST-API (not SSH) login is correct.
You may test this by logging in into the SPP-Website with the used credentials.
REST-API is not available due Config error
Exception in FILE: sppmon.py, Line: 411, Exception: <class 'ValueError'>
Exception Message: REST API login request not successfull.
Exception in FILE: sppmon.py, Line: 421, Exception: <class 'ValueError'>
Exception Message: System Methods are not available, missing api_queries.
Exception in FILE: sppmon.py, Line: 426, Exception: <class 'ValueError'>
Exception Message: Job Methods are not available, missing api_queries
Exception in FILE: sppmon.py, Line: 436, Exception: <class 'ValueError'>
Exception Message: Protection Methods are not available, missing api_queries
trying to open template dashboard on path c:\users\JasonBasler\source\repos\dash\SPPMON for IBM Spectrum Protect Plus.json
```

**Comment by nkrs44** [comment]
Assuming there were not further errors beside log messages about the dashboard creation:

Those errors are caused by the `optional_args`-setup. If any optional args are not available when calling sppmon, those errors will be shown, even if they arn't required for the certain argument you are calling.  This is only a problem if a `critical_arg` isn't available, since then sppmon will shut down. For now, only the connection to the influxdb as well as the config-file is critical and required for anything to work.

It is very hard to split those errors from some special args like the `--create_dashboard`, since a change would have wide effects and would make the project more complicated, even though allowing small improvements.

It would be possible to change the lines (and methods)
```
self.setup_args()
self.set_critial_configs(config_file)
self.set_optional_configs(config_file)
```
within the `__init__` method of sppmon to only setup args required for certain program calls. This would solve our issue, but create two new ones:
1. The easy one, you have to check your existing args which components they use and get a common ground over all args. It would be possible to solve this issue with some booleans and a dict uncomplicated
2. The hard/annoying one, you have to make sure in every program call, that all required components are initialized. 

This requires that on every new argument you have to check if all required components are available and also to add your requirements into the `setup_args`method.
I do not believe this is worth the improvement, especially since any arg do work without a connection to the SPP-Server (as long as all critical configs - influxdb - are available).

If you still wish to implement it, i might be able to do it as a new issue for further improvements.

**Comment by nkrs44** [comment]
@baslerj  FYI: I'm now in holidays for two weeks and probably start to work again on 01.11.

**Comment by baslerj** [comment]
This issue has been resolved with the test_connection changes.

```
docker run --rm -v /home/jbasler/sppmon_vm10.conf:/usr/src/app/sppmon.conf:ro,Z -v /home/jbasler/sppmonLogs:/root/sppmonLogs:Z sppmon python sppmon.py --cfg=sppmon.conf --create_dashboard --dashboard_folder_path=/root/sppmonLogs/dash
Starting SPPMon
Setting up configurations
> WARNING: An option for a utility operation has been specified.  Bypassing normal SPPMON operation.
Starting argument execution
> trying to open template dashboard on path /root/sppmonLogs/dash/SPPMON for IBM Spectrum Protect Plus.json
> Sucessfully opened. Creating new Dashboard
> finished creating content of dashboard
> trying to create dashboard file on path /root/sppmonLogs/dash/SPPMON for IBM Spectrum Protect Plus sppmon.json
> Sucessfully created new dashboard file.


!!! script completed !!!
```
