### ISSUE TITLE
Missing job errors and backup success rate

### ISSUE THREAD

**Issue by marcinlubojanski** [IBM/spectrum-protect-sppmon#13]
I find it strange that such a basic reports - job errors and backup success rate are not added to the default dashboard in Grafana. 
This is normally what each backup person is checking every day on all backup tools... I believe it should be added on the very top. 

Also when looking at influxdb (at least in my case) jobs and jobLogs tables are empty, despite it seems to be gathering them:

```
> getting joblogs for jobsessions without saved logs
>> requesting jobList from database
>>> number of jobs with no joblogs stored in Influx database: 47
>>> requested joblogs for 0 / 47 job sessions.
>>> requested joblogs for 5 / 47 job sessions.
>>> requested joblogs for 10 / 47 job sessions.
>>> requested joblogs for 15 / 47 job sessions.
>>> requested joblogs for 20 / 47 job sessions.
>>> requested joblogs for 25 / 47 job sessions.
>>> requested joblogs for 30 / 47 job sessions.
>>> requested joblogs for 35 / 47 job sessions.
>>> requested joblogs for 40 / 47 job sessions.
>>> requested joblogs for 45 / 47 job sessions.
>>> inserted a total of 3332 logs
Storing script metrics
Stored script metrics sucessfull
```

**Comment by nkrs44** [comment]
I'm up for suggestion on how to arrange for all 3 views: 14 days, 90 and 
multiple server(prob same as 14). I've spend a lot of time arranging 
them to fit into one screen and look good, you will probably need to 
replace something instead if simply adding. What would you suggest?

Just a short notice on not showing the logs:

Thats because they are saved into a different retention policy. Try

``` Select * from rp_days_90.jobs where $timefilter

```

Replace Timefilter with your time range. `rp_days_14` is the default 
one, joblogs are saved into `rp_half_year`

**Comment by marcinlubojanski** [comment]
Yes, data are there:

[root@shspbli23832547 config_files]# influx -ssl -unsafeSsl -username xxx -password 'xxx' -database 'mssql' -execute 'Select * from rp_days_90.jobs' |  more
name: jobs
time                duration  end        id            jobId jobLogsCount jobName                       jobsLogsStored start      status    subPolicyType type
----                --------  ---        --            ----- ------------ -------                       -------------- -----      ------    ------------- ----
1594857600000000000 965267    1594858566 1594857600178 1039               sql_bar_21d_prod_DCTM                        1594857600 COMPLETED BACKUP        protec
tion
1594857600000000000 893887    1594858494 1594857600174 1020               sql_bar_21d_prod                             1594857600 COMPLETED REPLICATION   protec
tion
1594857601000000000 613097    1594858214 1594857600237 1038               sql_arh_21d_prod_DCTM                        1594857601 PARTIAL   BACKUP        protec
tion
1594857601000000000 855966    1594858456 1594857600179 1018               sql_anw_21d_prod                             1594857601 PARTIAL   BACKUP        protec
tion
1594857601000000000 1878923   1594859480 1594857600182 1016               sql_arh_21d_prod                             1594857601 PARTIAL   BACKUP        protec
tion
1594857601000000000 2315      1594857603 1594857600242 1038               sql_arh_21d_prod_DCTM                        1594857601 ABORTED   SPPOFFLOAD    protec
tion
1594859400000000000 329414    1594859729 1594859400047 1039               sql_bar_21d_prod_DCTM                        1594859400 COMPLETED REPLICATION   protec
tion
1594859400000000000           1595925847 1594859400061 1038               sql_arh_21d_prod_DCTM                        1594859400 ABORTED   REPLICATION   protec
tion
1594861200000000000 628093    1594861828 1594861200072 1019               sql_shs_21d_prod                             1594861200 COMPLETED REPLICATION   protec
tion
1594861200000000000 552818    1594861753 1594861200076 1039               sql_bar_21d_prod_DCTM                        1594861200 COMPLETED BACKUP        protec
tion
1594861201000000000 525081    1594861726 1594861200102 1038               sql_arh_21d_prod_DCTM                        1594861201 PARTIAL   BACKUP        protec
tion

Is there somewhere also details on the partial completion how many VMs/DBs were backed up successfuly (f.e. 75/80 as displayed on SPP itself)  ?
I would love to have on dashboard all FAILED and PARTIAL status jobs as well as % success rate. Any idea how to add it there?

There was also request from our customer to have separate dashboard per SLA policy. Do you think it's doable ?

**Comment by marcinlubojanski** [comment]
I have edited the default dashboard and added job details. 
I would love to see there also % of successful backups :) but not sure how to add it.

![SPPMON_dashboard](https://user-images.githubusercontent.com/63609019/96153763-57af5800-0f0e-11eb-87f8-9cf2b5a75f16.jpg)

**Comment by NielsKorschinsky** [comment]
Hello @marcinlubojanski ,

Those %-Completion numbers are new in SPP 10.1.6. Since SPPMon was created in 10.1.5 I wasn't able to include them and you can't display them.
I will try to request those new numbers from the spp server. I will reach back out to you once i've completed it. 

I'm not sure what exactly your customer wants to see on the split via SLA. Could you provide some more information on this topic?

Thanks for your Screenshot! I might take it as inspiration to generate a Jobs Overview and create a merge request. If you have already another version with improved panels / organization, feel free to share it with me.

**Comment by marcinlubojanski** [comment]
No, dashboard was not edited since the print screen. 
I have exported it, so you can copy/megre it to the project. Attaching here. 
[SPPMON_grafana_dashboard.zip](https://github.com/IBM/spectrum-protect-sppmon/files/5517993/SPPMON_grafana_dashboard.zip)


As for the SLA split - we have several SPP split by technologies (SPP for MSSQL, for OpenShift, for VMware etc.) and then on each SPP we have separate vsnaps and policies per tenant. Now customer wants to see how their backup is performing but they should be able to see only what is relevant for the tenant, not all of them (this view will be available only to backup team/SPP admins). Is that more clear now ?

**Comment by NielsKorschinsky** [comment]
Sorry for the very late response.
I've implemented now more job statistics which you can request within the table `jobs_statistics` and `jobs` itself:
| Table | Field / Tag | Name | Description |
| ------ | ----- | ------ | ------ |
|  jobs |  Field | numTasks | meaning unknown for me yet |
| jobs | Field | percent | Percent of completion, still testing to do |
| jobs | Tag | indexStatus | Status of indexing |
| ------ | ----- | ------ | ----- |
| jobs_statistics | Field | id | id of the individual job execution, dropped on retention |
| jobs_statistics | Field | total | total count of `resourceType` backuped |
| jobs_statistics | Field | success | successful count of `resourceType` backuped |
| jobs_statistics | Field | failed| failed count of `resourceType` backuped |
| jobs_statistics | Field | skipped | skipped count of `resourceType` backuped. Note, sometimes calculated from other values |
| jobs_statistics | Tag | resourceType | type of backuped resource, examples: `vm`, `database`, `datastore` or empty. |
| jobs_statistics | Tag | indexStatus | Status of indexing of the associated job |

In addition both tables share the same Tags to identifiy each job type and job id to allow grouping and joining.


I've checked your board finally. I've modified both querys, especially the list of unsucessful job's to use the interface of grafana instead of an text query. Therefore the transform to hide `duration` and `id` weren't necessary anymore. Also You can now switch between a count all failed queries in the last  14 days to a list of all failed individually.

![jobs_marcoinlubojanski](https://user-images.githubusercontent.com/49568673/101773074-8ef44c80-3aec-11eb-85d8-56b826f26e89.png)

![grafik](https://user-images.githubusercontent.com/49568673/101772383-9830e980-3aeb-11eb-8502-94dcb5792511.png)

Thanks again for those examples. I've added them to our dashboard. I'm creating an additional comment on your SLA-Question.

**Comment by NielsKorschinsky** [comment]
You may want to re-import or compare our new dashboard since I've already added the addtional job statistics in their own panels in a new row below the jobs. Your Panels are also in there.
Once the merge request #29  is merged, those dashboards will be available on the dev branch.

**Comment by NielsKorschinsky** [comment]
> As for the SLA split - we have several SPP split by technologies (SPP for MSSQL, for OpenShift, for VMware etc.) and then on each SPP we have separate vsnaps and policies per tenant. Now customer wants to see how their backup is performing but they should be able to see only what is relevant for the tenant, not all of them (this view will be available only to backup team/SPP admins). Is that more clear now ?

I think the only way to achive this is to filter each panel with `sla_policy = CUSTOMERS_SLA`. \
To do so, you could setup a variable (like the `$SPP_Server` in the 90-day view with multiple select) to declare each SLA which should be available to be shown. \
Then you could filter on this variable and show the customer only his SLA's. This will also work by manually adding the SLA's without a variable.
Be aware that only the `jobs` and `job_statistics` table have the SLA-Tag. You may only filter them, though i guess your customer does not need to see the others / they show a general server performance.

If you need further help you can also reach out to me via slack. I'm closing since #29 should contain everything, feel free to reopen or comment if you want furthr information/help.
