### ISSUE TITLE
VM counts are not accurate (too low) from the vms measurement.

### ISSUE THREAD

**Issue by baslerj** [IBM/spectrum-protect-sppmon#6]
In an environment with more than 3000 VMs, less than 100 are being tracked in the vms measurement in influx.  This can be seen several panels under "VMware and Hyper-V Statistics"

**Comment by nkrs44** [comment]
If i remember correctly, that changed from one day to another, middle in august by an update. 
Best would be if you debug SPPMon, setting a breakpoint in the API_Queries Module, on the get_vms-request method, on the return value. Check by yourself if the error is in saving the data or if the error is caused by the REST-API of the SPP-Server.

I'm not able to check it myself since i do not have an accessible SPP-Server without a VPN login.

**Comment by nkrs44** [comment]
You can maybe check old data for the drop, it shouldnt be older than 90 days.

**Comment by baslerj** [comment]
I have debugged this issue some more.  The REST API query handling looks good as it loops through several pages of results.  This debug line indicates the result list matches the 3540 VMs that SPP has in the inventory.

`2020-09-27 17:49:29,771:[PID 23232]:DEBUG:rest_client.get_objects> objectList size 3540`

A bit further in the log I see this exception while processing sppmon.store_script_metrics(),  I will see if I can confirm there is a missing column and whether we need to modify the exception handling around this.

```
2020-09-27 17:49:42,101:[PID 23232]:ERROR:execption_utils.error_message> Not all columns for table sppmon_metrics are declared: vms
2020-09-27 17:49:42,454:[PID 23232]:INFO:sppmon.store_script_metrics> Stored script metrics sucessfull
2020-09-27 17:49:42,456:[PID 23232]:DEBUG:influx_client.disconnect> disconnecting Influx database
2020-09-27 17:49:43,500:[PID 23232]:DEBUG:rest_client.logout> Rest-API logout successfull
2020-09-27 17:49:43,500:[PID 23232]:INFO:sppmon.exit> 

!!! script completed !!!
```

**Comment by nkrs44** [comment]
Okay, now i understand the issue. 
There is a bug when naming the tables, it seems like somewhere in the path or saving the vm's, the tablename has a typo.
The Data is now saved in a different table, while sppmon.py warns us of this bug. i will try to debug this later without access if possible.

**Comment by nkrs44** [comment]
Protection.py, line 152:
```
if(self.__verbose):
            LOGGER.info(f"found {len(all_vms_list)} vm's.")
```
If you run with VERBOSE, how many VM's do you count here?
I assume it should be the same number as you recorded here and this would conclude, that the Python-Program is not the issue of the wrong number.
I assume, that the `insert_dicts_to_buffer` works correctly since a error there would be very unlikley in this regard.

I suggest to check for the error within the Grafana-Panel, maybe the query is corrupted or asking the wrong data, check whether the queried table is `vms`.

If the `vmstats`-table is used for displaying the data, the issue might be within the counting of the vm's. To trace down this issue, please debug the `part 2` of the `create_inventory_summary` method (line 203, protection.py).
- does the `all_vms_list` in line 226 contain >3000 vms?
- is the count in line 234 saved correctly?

If there is still no discrepancy found, you may have to check the continuous queries if there is a error on downsampling the data.

**Comment by nkrs44** [comment]
About the `missing collum`-error:
This is a very minor error, please just add ``"vms"` into the Tag-List in the module `defintions.py` on line 393:
```
cls.__add_predef_table(
            name='sppmon_metrics',
            fields={
                'duration':         Datatype.INT,
                'errorCount':       Datatype.INT,
                'errorMessages':    Datatype.STRING
            },
            tags=[
                'sppmon_version',
                'spp_version',
                'vms',
                 ....
```

**Comment by baslerj** [comment]
I have tracked down the problem and pushed a potential fix in branch _issue_6_missingVMs_.  Please review the changes if you have time.  I added the missing tags column to the definition sppmon_metrics table and that corrected the minor missing column issue as you have suspected.  I also added some more debugging to insert_dicts_to_buffer() that confirmed we were getting the sames number of VMs back from REST query that are being added to the insert buffer.

```
2020-09-28 16:58:33,186:[PID 20008]:INFO:protection.store_vms> found 3541 vm's.
2020-09-28 16:58:33,187:[PID 20008]:DEBUG:influx_client.insert_dicts_to_buffer> Enter
2020-09-28 16:58:39,757:[PID 20008]:DEBUG:influx_client.insert_dicts_to_buffer> Appended 3541 items to the insert buffer
2020-09-28 16:58:39,757:[PID 20008]:DEBUG:influx_client.insert_dicts_to_buffer> Exit
```
The issue turned out to be with the definition of the vms table.  I dropped my existing vms measurement from the influx studio and allowed it to be created again from scratch.  Of the 3541 VMs added to the insert buffer, only a small fraction were actually created in influx.  The root caused turned out to be Influx treating most of the data points as duplicates.  The table definition has _time_key='catalogTime'_ and the REST query has an identical timestamp for all 3541 VMs.  The _id_ field is unique for every VM and we are not using that field for any graphs, so I moved it from **fields** to **tags** so that Influx will see each data point as unique since most of the other tags are duplicated throughout our test data set.

With this change in place, all 3541 VMs are now successfully inserted into the table and the VM report is rendering as expected now.
```
            fields={
                'uptime':           Datatype.TIMESTAMP,
                'powerState':       Datatype.STRING,
                'commited':         Datatype.INT,
                'uncommited':       Datatype.INT,
                'shared':           Datatype.INT,
                'cpu':              Datatype.INT,
                'coresPerCpu':      Datatype.INT,
                'memory':           Datatype.INT,
                'name':             Datatype.STRING
            },
            tags=[
                'host',
                'vmVersion',
                'osName',
                'isProtected',
                'inHLO',
                'isEncrypted',
                'datacenterName',
                'id',                   # For issue #6, moved id to tags from fields to ensure uniqueness in tag set
                'hypervisorType'
            ],
            time_key='catalogTime',
```

**Comment by nkrs44** [comment]
Good that you found the bug and nice debug-infos. Since we only capture the debug level if --debug is enabled, the spam caused by inserts wont matter and help a lot.

About the bug and the fix:
I've actually removed the ID on purpose. We are able to save up to 100.000 distinct tag values per Tag with the influxDB, the `vm_id` is able to hit that limit over some time. Even reaching the limit will probably slow the database down, especially if you observe multiple servers at once.

I would like to keep the ID out, it adds no useful statistical factor and is instantly purged on the continuous query (we cannot group by ID or it wont correctly aggregate `vmstats`). Still, i do not know a valid way to prevent the influxdb from purging, adjusting the timestamp isn't a option either (in short, its rounded on MS and we do not want to split the recording over 10.000 ms). 
Let me gather more information about the relevance of the tag-value limit, but i guess we don't have any choice but re-adding the `id`.

**Comment by nkrs44** [comment]
I'd like to keep this issue open until i checked the consequences of reaching the tag limit. I had no time yet to do my research on leaving the `id` as tag. It should increase the cardinality  possibly a lot, slowing down the influxdb and beeing a long term issue.
It is not recommended by influx to use id's as tags, since those possibly create a unbound cardinality.

I'm currently requesting further information, it may be useful if you run the cardinality command on the vm-measurment.

Cardinality:
https://www.influxdata.com/blog/data-layout-and-schema-design-best-practices-for-influxdb/
https://docs.influxdata.com/influxdb/v1.8/concepts/glossary/#series-cardinality
https://www.influxdata.com/blog/tldr-influxdb-tech-tips-december-15-2016/

`Show cardinality`-Command: 
https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-measurement-cardinality
