### ISSUE TITLE
Changing retention policies in InfluxDB is not persistent

### ISSUE THREAD

**Issue by falkobanaszak** [IBM/spectrum-protect-sppmon#62]
Hi everyone,
we would like to change the retention of the collected data to 1 year.
However, simply creating a new retention policy on the specified database for the SPP GUI host, does not work. 
We used:

```
use DATABASE
show retention policies
DROP RETENTION POLICY "rp_one_year" ON DATABASE
CREATE RETENTION POLICY "rp_one_year" ON DATABASE DURATION 365d REPLICATION 1 DEFAULT
show retention policies
```
Unfortunately, the retention policy sticks there for 10 seconds and is reverted to the "rp_days_14" retention policy again.

We found that the policy is also stated in the JSON model files for each SPP Host.

![image](https://user-images.githubusercontent.com/45035214/121152376-6c49b300-c845-11eb-9c34-d3332c302c63.png)

After changing these values to our desired 1 year retention, it didn't work.

Lastly, we would like to know how we can retain 1 year of data of all our SPP Hosts ?
Thanks for the input !

**Comment by NielsKorschinsky** [comment]
Hello @falkobanaszak,

In the current version sppmon validates and alters retention-policy settings with each execution of sppmon.py to make sure no changes are stopping data from beeing saved, as well as allowing an easier way to display the data. Another requirement to enforce this rule is that the saving process is quite complex, having some data directly split up between different retention policies.

This means, each time when you execute sppmon to collect data, any changes to the database are set to the defaults specified within the code. If you want to have any changes persistent, you may have to change some settings within the code.
You may check out the file `spectrum-protect-sppmon/python/influx/definitions.py`, line 80 for this, as well as line 293+

Please be aware that the individual retention policies are hierarchical:
1. `rp_days_14`: Saves **some of the data** for 14 days, having a high data point count (examples: CPU, RAM)
2. `rp_days_90`: Saves **all data** for 90 days, having a medium data point count (Examples: job executions, downscaled CPU/RAM)
3. `rp_inf`: Saves **all data** on a downscaled version on a weekly basis.

Some data like the jobs-executions are only aquired once a day and not saved within the `rp_days_14` dashboard. Changes to this rp won't have any affect on these data. Also every (important) datapoint is downscaled over each retention policy with following grouping times if applicable: `full -> 6h/full -> 1 week` so your request might already be fulfilled by checking out the data of other retention policies. \
You may easily view the 90/Inf retention policy by importing the other dashboard within the `Grafana` folder: `SPPMON Long Term View (90 Days _ Infinite).json`

**If you really want to change the retention policy duration, you may do so by altering both `rp_days_14` and `rp_days_90` within the script mentioned above, without changing the name, only the duration**. Changing the assoicated retention policy in line 293+ is also possible, but requires more insight since you have to change it at multiple occasions, including the Grafana-Dashboard file screenshotted by you above.

```
@classmethod
    def _RP_DAYS_90(cls):
        """3 Month duration for either non-downsampled data of low count/day or medium-downsampled of high count/day."""
        return RetentionPolicy(name="rp_days_90", database=cls.__database, duration="90d")

    @classmethod
    def _RP_DAYS_14(cls):
        """2w duration for non-downsampled data of high count/day"""
        return RetentionPolicy(name="rp_days_14", database=cls.__database, duration="14d", default=True)
```
to 
```
@classmethod
    def _RP_DAYS_90(cls):
        """3 Month duration for either non-downsampled data of low count/day or medium-downsampled of high count/day."""
        return RetentionPolicy(name="rp_days_90", database=cls.__database, duration="56w")

    @classmethod
    def _RP_DAYS_14(cls):
        """2w duration for non-downsampled data of high count/day"""
        return RetentionPolicy(name="rp_days_14", database=cls.__database, duration="56w", default=True)
```   
  
I know enforcing the default retention policies is not the best solution, but currently the most feasible solution.
Also due to the nature of SPPMon only data within the first 14 days is required with high datapoint rates since it is focused on the current state. By using the 90/Inf-Dashboard it is possible to detect trends and other issues by having a larger view which also doesn't require a high data point count.

If you have any further questions or request, please feel free to ask.
Would you suggest raising the minimal duration from 14 days to 30 days (and 90 Days -> 180 days)?

**Comment by falkobanaszak** [comment]
Hi @NielsKorschinsky,
thanks for the input so far.
So in fact we think that at least 180 days are useful in terms of checking trends and evaluating data.
We would also have no problem with the data which gets created !
Thanks for your input

**Comment by NielsKorschinsky** [comment]
You're welcome.
You may change this within the settings explained above. Still, I'd recommend to leave it on default since you can still view the data on a downsampled scale within the Grafana view for 90days/Infinite. 
If you have any issues with this or any further questions, feel free to re-open this issue!
