### ISSUE TITLE
Cardinality of the vms table

### ISSUE THREAD

**Issue by NielsKorschinsky** [IBM/spectrum-protect-sppmon#8]
I'm moving this into a new issue, since the bug is solved. Related to #6 .

It is unclear now, what are the consequences of reaching the tag limit. It is possible to increase it, but it might have a downside.

I had no time yet to do my research on leaving the `id` as tag. It should increase the cardinality  possibly a lot, slowing down the influxdb and beeing a long term issue. It is not recommended by influx to use id's as tags, since those possibly create a unbound cardinality.

I'm currently requesting further information, it may be useful if you run the cardinality command on the vm-measurment.

Cardinality:
https://www.influxdata.com/blog/data-layout-and-schema-design-best-practices-for-influxdb/
https://docs.influxdata.com/influxdb/v1.8/concepts/glossary/#series-cardinality
https://www.influxdata.com/blog/tldr-influxdb-tech-tips-december-15-2016/

`Show cardinality`-Command: 
https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-measurement-cardinality

**Comment by baslerj** [comment]
Interesting topic.  I will continue to run with the current fix and watch for problems.  So far memory consumption and performance looks fine.  The infrequency of inserting samples to vms may avoid problems.  Here are a few samples after about four occurrences of running sppmon with --vms.

```
> show tag values cardinality with key=id
name: vms
count
-----
3928

name: vsnap_pools
count
-----
1
> show series cardinality
cardinality estimation
----------------------
52604
> show measurement cardinality
cardinality estimation
----------------------
21
```

**Comment by baslerj** [comment]
@nkrs44 If we figure out a way to guarantee unique timestamps for each entry would that reduce the cardinality problems?

**Comment by nkrs44** [comment]
I've had the same idea as well as someone in the Influxdb-Slack, but I think it would be a bit akward.
We currently use ms-precision, any ns-precision is cutted by both sppmon.py to avoid problems, i believe the database also does this step. The implementation would actually be quite easy.

This would mean to potentially split vms over a time of 10 seconds, it could work, since only aquire them once a day, but its a quite heavy workaround.
If the cardinality tends to be a problem, we can surly do this.


As far as I see, a cardinality of 52k isnt too bad for an estimate. I believe the true numbers are a bit lower, since not every permutation of id + other tags occurs, but quite similar values. 
It is possible to raise the tag limit above 100k, but i would avoid doing it as long as possible and then really rather go with our timestamp-fix.

**Comment by nkrs44** [comment]
[Troubleshooting Cardinality.pdf](https://github.com/IBM/spectrum-protect-sppmon/files/5316599/Troubleshooting.Cardinality.pdf)
I did some talking within the Influxdb-Slack and got this document which is about to be released by them. Still, I have not got any real information how big this issue is going to be. 

Since we do retention on a 14 day bias, i would for now ignore this potential issue and check later on, if this is a problem. We could maybe do this by checking if the cardinality gets increased over time or not.
I'd like to keep the issue open.

**Comment by NielsKorschinsky** [comment]
Closing this now since I've had some feedback in the slack channel saying that such a cardinality should not be a problem. Also there is no real fix in sight. If this is getting a problem later on, we can revistit this topic.
