### ISSUE TITLE
parsing exception for ssh results when a vSNAP server is not online

### ISSUE THREAD

**Issue by baslerj** [IBM/spectrum-protect-sppmon#84]
The following parsing error was observed:
`Exception in FILE: influx_client.py, Line: 646, Exception: <class 'influxdb.exceptions.InfluxDBClientError'>
Exception Message: 400: {"error":"partial write: unable to parse 'vsnap_pools,encryption_enabled=False,id=1,name=primary,pool_type=raid0,status=Unknown,hostName=x.x.x.x,ssh_type=VSNAP compression_ratio=1.00x,deduplication_ratio=1.00x,diskgroup_size=1i,health=0i 1641493989': invalid number dropped=0"}
Some messages were lost when sending buffer for table vsnap_pools, but everything else should be OK
Storing script metrics
total of 7 exception/s occured
`

Running vsnap pool show on the remote system indicates there is a problem with the vsnap pool.  I recommend matching cases where state != "ONLINE" and making an update the will reflect the error condition in a vsnap status report.

` sudo vsnap pool show
TOTAL: 1

ID: 1
NAME: primary
POOL TYPE: raid0
STATUS: Unknown
HEALTH: No
`

**Comment by NielsKorschinsky** [comment]
@baslerj  It seems like the issue is that the compression ratio and dedup-ratio includes now a `x`, instead of beeing a pure float.

A few important questions:
* does this vsnap have compression and dedup enabled?
* Is 1.00 a correct value or only a placeholder due to the vsnap beeing unavailable?
* Do the other values look regular to you or is there anything else I need to ignore if the status is `UNKNOWN`?

If the values are fine, I would only trim out the x to allow processing of these stats again.
If the 1.00 values are placeholders I will cut out any invalid datapoints.

**Comment by NielsKorschinsky** [comment]
@baslerj tried to recreate this issue with a DEGRADED state, but it seems like this issue is either fixed or very depended on the UNKNOWN status.
Due to PR #87 the vsnap-API will most likely only be called when it is full/mostly available, preventing a UNKNOWN state.
If this error occurs again a hotfix can be deployed, implementing it now would only bloat the code unnecessary.
